<a href="https://colab.research.google.com/github/makena-yvonne/Countdown/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [ ]:
#Basic Numpy Arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])


In [ ]:
a[0], a[1]

In [ ]:
a[0:]

In [ ]:
a[1:3]

In [ ]:
a[1:-1]

In [ ]:
a[::2]

In [ ]:
b


In [ ]:
b[0], b[2], b[-1]

In [ ]:
b[[0,2,-1]]

In [ ]:
#Array Types
a

In [ ]:
a.dtype

In [ ]:
b

In [ ]:
b.dtype

In [ ]:
np.array([1,2,3,4], dtype=np.float)

In [ ]:
array([1,2,3,4], dtype=int8)

In [ ]:
c=np.array(['a','b','c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d=np.array([{'a':1}, sys])

In [ ]:
d.dtype

dtype('O')

In [ ]:
#Dimensions and shapes


In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B=np.array([
            [
             [12,11,18],
             [9,8,7],
            ],
            [
             [6,5,4],
             [3,2,1]
            ]
])

In [ ]:
B

array([[[12, 11, 18],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
C=np.array([
            [
             [12,11,18],
             [9,8,7],
            ],
            [
             [6,5,4]
            ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
C(type[0])

TypeError: ignored

In [ ]:
#Indexing and Slicing of Matrices
#Square matrix
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10,10,10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2]=99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [ ]:
#Summary Statistics
a=np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
#per column
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
#per row
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])