<a href="https://colab.research.google.com/github/makena-yvonne/Countdown/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

In [2]:
#Basic Numpy Arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])


In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b


array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0,2,-1]]

array([0., 1., 2.])

In [13]:
#Array Types
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [18]:
array([1,2,3,4], dtype=int8)

NameError: ignored

In [ ]:
c=np.array(['a','b','c'])

In [ ]:
c.dtype

In [ ]:
d=np.array([{'a':1}, sys])

In [ ]:
d.dtype

In [ ]:
#Dimensions and shapes


In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6]
])

In [ ]:
A.shape

In [ ]:
A.ndim

In [ ]:
A.size

In [ ]:
B=np.array([
            [
             [12,11,18],
             [9,8,7],
            ],
            [
             [6,5,4],
             [3,2,1]
            ]
])

In [ ]:
B

In [ ]:
B.shape

In [ ]:
B.ndim

In [ ]:
B.size

In [ ]:
C=np.array([
            [
             [12,11,18],
             [9,8,7],
            ],
            [
             [6,5,4]
            ]
])

In [ ]:
C.dtype

In [ ]:
C.shape

In [ ]:
C.size

In [ ]:
C(type[0])

In [ ]:
#Indexing and Slicing of Matrices
#Square matrix
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

In [ ]:
A[1]

In [ ]:
A[1][0]

In [ ]:
A[0:2]

In [ ]:
A[:, :2]

In [ ]:
A[:2, :2]

In [ ]:
A[:2, 2:]

In [ ]:
A

In [ ]:
A[1] = np.array([10,10,10])

In [ ]:
A

In [ ]:
A

In [ ]:
A[2]=99

In [ ]:
A

In [ ]:
#Summary Statistics
a=np.array([1,2,3,4])

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a.var()

In [ ]:
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.std()

In [ ]:
#per column
A.sum(axis=0)

In [ ]:
#per row
A.sum(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A.std(axis=0)

In [ ]:
A.std(axis=1)

In [ ]:
#Broadcasting and vectorized operations
a = np.arange(4)

In [ ]:
a

In [ ]:
a+10

In [ ]:
a*10

In [ ]:
a

In [ ]:
a+=100

In [ ]:
a

In [ ]:
l=[0,1,2,3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a=np.arange(4)

In [ ]:
a

In [ ]:
b=np.array([10,10,10,10])

In [ ]:
b

In [ ]:
a+b

In [ ]:
a*b

In [ ]:
a = np.arange(5)

In [ ]:
a+20

In [ ]:
a

In [ ]:
#Boolean arrays


In [ ]:
a=np.arange(4)

In [ ]:
a

In [ ]:
a[0], a[-1]

In [ ]:
a[[0,-1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a >= 2

In [ ]:
a[a>=2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a==1)]

In [ ]:
a[(a<=2) & (a%2==0)]

In [20]:
A = np.random.randint(100, size=(3,3))

In [21]:
A

array([[75, 25, 10],
       [61, 55, 70],
       [95, 16, 24]])

In [22]:
A[np.array([
            [True, False, True],
            [False, True, False],
            [True, False, True]
]
    )]

array([75, 10, 55, 95, 24])

In [23]:
A > 30

array([[ True, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [24]:
A[A > 30]

array([75, 61, 55, 70, 95])

In [28]:
#Linear Algebra 
A = np.array ([
               [1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
])

In [29]:
B = np.array([
              [6, 5],
              [4, 3],
              [2, 1]
])

In [30]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [31]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [32]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [41]:
#Size of objects in Memory
#Int, floats
#An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [39]:
#Longs are even larger
sys.getsizeof(10 ** 100)

72

In [44]:
#Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [42]:
np.dtype(float).itemsize

8

In [43]:
#Lists are even larger
#A one-element List
sys.getsizeof(1)

28

In [45]:
#An array of one element is numpy
np.array([1]).nbytes

8

In [53]:
#And performance is also important
l = list(range(100000))

In [54]:
a =np.arange(100000)

In [55]:
%time np.sum( a ** 2)

CPU times: user 1.15 ms, sys: 844 µs, total: 2 ms
Wall time: 2.15 ms


333328333350000

In [56]:
%time sum ([x ** 2 for x in l])

CPU times: user 37.5 ms, sys: 4.97 ms, total: 42.5 ms
Wall time: 42.8 ms


333328333350000

In [57]:
#Useful Numpy functions
#random
np.random.random(size=2)

array([0.46005636, 0.05264566])

In [58]:
np.random.normal(size=2)

array([ 0.7040023 , -0.87779268])

In [59]:
np.random.rand(2, 4)

array([[0.44372423, 0.80883369, 0.86599501, 0.4422873 ],
       [0.37939399, 0.03575833, 0.4122063 , 0.88400621]])

In [60]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [27]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [62]:
#reshape
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
#linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [66]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [68]:
np.linspace(0,1,20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [69]:
#zeros, ones, empty
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [74]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [78]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [79]:
#identity and eye
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
"Hello World"[6]

'W'